AWSTemplateFormatVersion: "2010-09-09"
Description: Create frontend base

################# Input parameters ###############
Parameters:
  Prefix:
    Default: sbcntr
    Type: String
  VpcId:
    Description : Input 'sbcntr' VPC ID
    Type: AWS::EC2::VPC::Id
# ALB 
  ALBSecurityGroupId:
    Description: Input 'ingress' SecurityGroup ID
    Type: AWS::EC2::SecurityGroup::Id
  ALBSubnetId1:
    Description : Input 'ingress' Subnet ID for ap-northeast-1a
    Type : AWS::EC2::Subnet::Id
  ALBSubnetId2:
    Description : Input 'ingress' Subnet ID for ap-northeast-1c
    Type : AWS::EC2::Subnet::Id
# Service Discovery
  BackendHost:
    Description : Input service discovery name for backend service
    Type: String
    Defualt: sbcntr-ecs-backend-service.local


Resources:
  ############### ECS ###############
  sbcntrECSClusterFrontend:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${Prefix}-frontend-cluster"
  sbcntrTaskDefinitionFrontend:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${Prefix}-frontend-def"
      ContainerDefinitions:
        - Name: app
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/sbcntr-frontend:v1"
          Essential: true
          Cpu: 256
          MemoryReservation: 512
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
          Environment:
            - Name: SESSION_SECRET_KEY
              Value: 41b678c65b37bf99c37bcab522802760
            - Name: APP_SERVICE_HOST
              Value: !Sub "http://${BackendHost}"
            - Name: NOTIF_SERVICE_HOST
              Value: !Sub "http://${BackendHost}"
          LogConfiguration:
              LogDriver: awslogs
              Options: 
                awslogs-group: !Sub "/ecs/${Prefix}-frontend-def"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: ecs
      Cpu: 512
      Memory: 1024
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
  sbcntrCloudWatchLogsFrontend:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/sbcntr-frontend-def
      RetentionInDays: 14
    UpdateReplacePolicy: Retain

  ############### Application Load Balancer ###############    
  sbcntrAlbFrontend:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${Prefix}-alb-ingress-frontend"
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Subnets:
        - !Ref ALBSubnetId1
        - !Ref ALBSubnetId2
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: false
  sbcntrTargetGroupFrontend:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${Prefix}-tg-frontend"
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckIntervalSeconds: 15
      HealthCheckPath: /healthcheck
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher: 
        HttpCode: 200
      VpcId: !Ref VpcId
  sbcntrFrontendListener1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
        DefaultActions: 
          - TargetGroupArn: !Ref sbcntrTargetGroupFrontend
            Type: forward
        LoadBalancerArn: !Ref sbcntrAlbFrontend
        Port: 80
        Protocol: HTTP

