CREATE USER sbcntruser WITH PASSWORD 'sbcntrEncP';
GRANT CONNECT ON DATABASE app TO sbcntruser;
GRANT USAGE ON SCHEMA public TO sbcntruser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sbcntruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sbcntruser;
